services:
#    ribs_framework.example:
#        class: Ribs\FrameworkBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    # EntityListeners
    Ribs\RibsAdminBundle\EventListener\GuidAwareListener:
        arguments: [ "@service_container" ]
        tags:
            - { name: doctrine.orm.entity_listener }

    ribs_admin.acess_rights:
        class: Ribs\RibsAdminBundle\Service\AccessRights
        arguments: ['@service_container', "@router", "@session", "@request_stack"]
        tags:
            - {name: kernel.event_listener, event: kernel.controller}

    ribs_admin.globals:
        class: Ribs\RibsAdminBundle\Service\Globals