parameters:
    ribs_admin.dev_mode: false
    ribs_admin.api_token_duration: 120
    ribs_admin.paginator_element_per_page: 20
    ribs_admin.base_upload_url: ''
    ribs_admin.upload_dir: ''
    ribs_admin.check_version_url: '%env(RIBS_ADMIN_CHECK_VERSION_URL)%'
    ribs_admin.allow_check_version_from_url: '%env(RIBS_ADMIN_ALLOW_CHECK_VERSION_FROM_URL)%'

services:
    PiouPiou\RibsAdminBundle\:
        resource: '../../*'
        exclude: '../../{Entity,Migrations,Tests}'

    PiouPiou\RibsAdminBundle\Controller\:
        resource: '../../Controller'
        calls:
            - [setContainer, ["@service_container"]]
        tags: ['controller.service_arguments']

    PiouPiou\RibsAdminBundle\Command\ImportModuleCommand:
        arguments: [ "@doctrine.orm.default_entity_manager" ]
        tags:
            - { name: 'console.command', command: 'ribsadmin:import-module' }

    PiouPiou\RibsAdminBundle\Command\CreateAdminCommand:
        arguments: [ "@doctrine.orm.default_entity_manager", "@security.password_encoder" ]
        tags:
            - { name: 'console.command', command: 'ribsadmin:create-admin' }

    PiouPiou\RibsAdminBundle\EventListener\GuidAwareListener:
        arguments: [ "@service_container" ]
        tags:
            - { name: doctrine.orm.entity_listener }

    PiouPiou\RibsAdminBundle\EventListener\CreateUpdateAwareListener:
        arguments: [ "@security.untracked_token_storage" ]
        tags:
            - { name: doctrine.orm.entity_listener }

    PiouPiou\RibsAdminBundle\Service\AccessRights:
        arguments: ['@service_container', "@router", "@session", "@request_stack", "@security.token_storage", "@ribs_admin.globals", "@ribs_admin.module_service", "@ribs_admin.api"]
        public: true

    PiouPiou\RibsAdminBundle\Service\UserLog:
        arguments: ["@security.token_storage", "@doctrine.orm.default_entity_manager"]
        tags:
            - {name: kernel.event_listener, event: kernel.request}
        public: true

    PiouPiou\RibsAdminBundle\Service\Globals:
        arguments: ['@service_container']
        public: true

    ribs_admin.acess_rights:
        class: PiouPiou\RibsAdminBundle\Service\AccessRights
        arguments: ['@service_container', "@router", "@session", "@request_stack", "@security.token_storage", "@ribs_admin.globals", "@ribs_admin.module_service", "@ribs_admin.api"]
        tags:
            - {name: kernel.event_listener, event: kernel.controller}
        public: true

    ribs_admin.globals:
        class: PiouPiou\RibsAdminBundle\Service\Globals
        arguments: ['@service_container']
        public: true

    ribs_admin.module_service:
        class: PiouPiou\RibsAdminBundle\Service\ModuleService
        arguments: ['@service_container', "@ribs_admin.globals"]
        public: true

    ribs_admin.api:
        class: PiouPiou\RibsAdminBundle\Service\Api
        arguments: ['@service_container', "@doctrine.orm.default_entity_manager", "@session", "@request_stack"]
        public: true

    PiouPiou\RibsAdminBundle\Service\ModuleService:
        arguments: ['@service_container', "@ribs_admin.globals"]
        public: true

    PiouPiou\RibsAdminBundle\Service\Api:
        arguments: ["@service_container","@doctrine.orm.default_entity_manager", "@session", "@request_stack"]
        public: true

    PiouPiou\RibsAdminBundle\Service\Version:
        arguments: [ "@doctrine.orm.default_entity_manager","@http_client" ]
        public: true

    #forms
    PiouPiou\RibsAdminBundle\Form\User:
        arguments: ['@doctrine.orm.entity_manager', '@security.token_storage']
        tags: [form.type]
