parameters:
    ribs_admin.dev_mode: false
    ribs_admin.api_token_duration: 120
    ribs_admin.paginator_element_per_page: 20
    ribs_admin.base_upload_url: ''
    ribs_admin.upload_dir: ''
    ribs_admin.packages_token: '%env(RIBS_ADMIN_TOKEN)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    PiouPiou\RibsAdminBundle\:
        resource: '../../*'
        exclude: '../../{Entity,Migrations,Tests}'

    PiouPiou\RibsAdminBundle\Controller\:
        resource: '../../Controller'
        calls:
            - [setContainer, ["@service_container"]]
        tags: ['controller.service_arguments']

    PiouPiou\RibsAdminBundle\EventListener\GuidAwareListener:
        tags:
            - { name: doctrine.orm.entity_listener }

    PiouPiou\RibsAdminBundle\EventListener\CreateUpdateAwareListener:
        tags:
            - { name: doctrine.orm.entity_listener }

    PiouPiou\RibsAdminBundle\EventListener\ExceptionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception }

    PiouPiou\RibsAdminBundle\Service\UserLog:
        tags:
            - { name: kernel.event_listener, event: kernel.request }

    ribs_admin.acess_rights:
        class: PiouPiou\RibsAdminBundle\Service\AccessRights
        tags:
            - { name: kernel.event_listener, event: kernel.controller }