name: CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Sleep for 720 seconds (12 minutes)
      uses: jakejarvis/wait-action@master
      with:
        time: '720s'
    - name: SSH Execute Commands
      uses: JimCronqvist/action-ssh@0.1.1
      with:
        command: /home/${{ secrets.DEV_SRV_USER }}/${{ secrets.SCRIPT }}.sh
        hosts: ${{ secrets.DEV_SRV_URL }}
        privateKey: ${{ secrets.SSH_KEY }}
    - name: Slack Notify
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_CHANNEL: github-actions
        SLACK_USERNAME: RibsGithub
        SLACK_TITLE: 'Ribs update'
        SLACK_MESSAGE: 'Ribs update is finished'
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
